#!/bin/bash
#=======================
# Author : Ali Moradzade
# Created: 2022/03/17
#=======================

#fix broken links

for dir in *
do
	if [ -d "$dir" ]
	then
		echo "processing $dir"
		cd "$dir"
		
		for f in *.ipynb
		do
			if [ -f "$f" ]
			then
				if grep -q "Pierian_Data_Logo.png" "$f" || grep -q "../Pierian_Data_Logo.PNG" "$f"
				then
 					# echo "$f --> contains"
					sed -i 's!../Pierian_Data_Logo.png!pierian-data-logo.png!' "$f"
					sed -i 's!../Pierian_Data_Logo.PNG!pierian-data-logo.png!' "$f"
				fi
			fi
		done

		echo "Done."
		echo
		cd ..
	fi
done
